apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: style-api-hpa
  namespace: style
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: style-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 15
